### PR TITLE
Added in Throwable class.(CanaryLib)

### PR DESCRIPTION
**Pull request by ghost**
Not hooked into server source yet.

### CODE REVIEW

**Comment by damagefilter** [comment]
Please rename it to EntityThrowable.
Also javaDocs go ABOVE methods and classes, not below them ... please fix that too.

**Comment by Jarvix** [comment]
Also, make getType return the enum item not a class.

**Comment by WWOL** [comment]
Also, you probably want a space between Entity and the opening bracket.
And I think the return for getSource() should be EntityLiving not CanaryEntityLiving. If you use CanaryEntityLiving then plugin devs using it need to also reference CanaryMod.jar as well as CanaryLib.jar.

WWOL

**Comment by ghost** [comment]
K.

**Pull request closed without merging**
