### PR TITLE
Added PluginDisableHook/PluginEnableHook/ServerListPingHook!

### PR DESCRIPTION
**Pull request by greatman**
Also added a fix for the unsafe loading. It was crashing if there was no dependency.

### CODE REVIEW

**Comment by greatman** [comment]
Ping hook, without touching the hook: http://i.imgur.com/497K2hq.png
With modifing the hook: http://i.imgur.com/aX5rDZr.png

**Comment by BluXDragon** [comment]
lol I suggested PluginEnableHook and one of the devs was just like "No."
But I want it so I can reload the properties (or plugin itself) of extension plugins when their parent gets reloaded.

Also 'dat coloured MOTD. Did you do something to add that? Because last I tried it wasn't possible.

**Comment by BluXDragon** [comment]
wtfu double post and clicking the delete button isn't doing anything.

**Comment by darkdiplomat** [comment]
@BluXDragon  we are looking into doing dependency reloading natively (though so far I haven't quite got it to function)

**Comment by greatman** [comment]
@BluXDragon The green MOTD is just the default color in Spoutcraft :P

**Pull request merged**
